### PR TITLE
chore: fix lint warnings

### LINKED ISSUE #1650: chore: resolve lint warnings - < Tipseen />, < Tooltip />, < TypographyHooks />, < VirtualizedList />, < VirtualizedGrid />
[Monday ticket](https://monday.monday.com/boards/3532714909/pulses/5311575773)

image

### PR DESCRIPTION
**Pull request by Dhoni77**
Closes #1650 

Fix lint warnings in  - < Tipseen />, < Tooltip />, < TypographyHooks />, < VirtualizedList />, < VirtualizedGrid />

### CODE REVIEW

File: src/components/VirtualizedList/VirtualizedList.tsx [hunk 1]
```diff
@@ -386,7 +394,7 @@ const VirtualizedList: VibeComponent<VirtualizedListProps> = forwardRef(
             updateListSize(width, height);
             return (
               <List
-                ref={mergedListRef}
+                ref={mergedListRef as unknown as LegacyRef<VariableSizeList<unknown>>}
```
Comment (SergeyRoyt) [inline src/components/VirtualizedList/VirtualizedList.tsx:397]:
```suggestion
                ref={listRef}
```
Cause it's anyway inside `mergedListRef`

File: src/components/VirtualizedGrid/VirtualizedGrid.tsx [hunk 2]
```diff
@@ -299,8 +299,7 @@ const VirtualizedGrid: VibeComponent<VirtualizedGridProps> = forwardRef(
                 onItemsRendered={onItemsRenderedCB}
                 className={scrollableClassName}
               >
-                {/*@ts-ignore*/}
-                {cellRenderer}
+                {cellRenderer as unknown as VibeComponent<GridChildComponentProps>}
```
Comment (SergeyRoyt) [inline src/components/VirtualizedGrid/VirtualizedGrid.tsx:302]: Not a fun of this one, but haven't found better solution, so let's consider this as good enough

**Review by SergeyRoyt — CHANGES_REQUESTED** [review]
Great job!
One commit suggestion to do and ready to go 👍

**Comment by SergeyRoyt** [comment]
Will fix `useMergeRef` return type in a separate PR and will tell u when to update from master 🙏

**Review by SergeyRoyt — CHANGES_REQUESTED** [review]
Hey, @Dhoni77 !
Sorry, didn't found time to finish to the `useMergeRefs` fix. Let's just revert the last commit then - it's good enough for now and we'll get back to it some other time 🙏
Thanks!

**Review by SergeyRoyt — APPROVED** [review]
Good enough! I'll fix the remaining issues. Thanks!
