### PR TITLE
fix: <Avatar> remove default tabIndex = 0

### LINKED ISSUE #1572: fix: <Avatar> remove default tabIndex = 0
Set default value of tabIndex equal to zero only if avatar is clickable or has a tooltip (please check this page https://style.monday.com/?path=/docs/media-avatar-avatar--avatar-with-tooltip)

Example of the issue - `ListItem`
image

### PR DESCRIPTION
**Pull request by Kritik-J**
Resolves #1572

### CODE REVIEW

File: src/components/Avatar/Avatar.tsx [hunk 1]
```diff
@@ -137,6 +137,15 @@ const Avatar: React.FC<AvatarProps> & {
...
   }, [size, topLeftBadgeProps, topRightBadgeProps, bottomLeftBadgeProps, bottomRightBadgeProps]);
 
+  const defaultTabIndex = useMemo(() => {
+    if (!!onClick || (tooltipProps && tooltipProps.content)) {
+      return 0;
+    }
+    return -1;
+  }, [onClick, tooltipProps]);
+
+  const tabIndexValue = tabIndex === undefined ? defaultTabIndex : tabIndex;
```
Comment (SergeyRoyt) [inline src/components/Avatar/Avatar.tsx:147]:
```suggestion
    const defaultTabIndex = useMemo(() => {
    if (!disabled && (onClick || overrideTooltipProps?.content)) {
      return 0;
    }
    return -1;
  }, [disabled, onClick, overrideTooltipProps?.content]);

  const overrideTabIndex = tabIndex ?? defaultTabIndex;
```

File: src/components/Avatar/Avatar.tsx [hunk 2]
```diff
@@ -179,7 +188,7 @@ const Avatar: React.FC<AvatarProps> & {
               avatarContentWrapperClassName
             )}
             aria-hidden={ariaHidden}
-            tabIndex={tabIndex}
+            tabIndex={tabIndexValue}
```
Comment (SergeyRoyt) [inline src/components/Avatar/Avatar.tsx:191]:
```suggestion
            tabIndex={overrideTabIndex}
```

**Review by SergeyRoyt — CHANGES_REQUESTED** [review]
Thanks! Proposed a few improvements
Please, also write some comment in the issue - can't assign you to it otherwise

**Review by SergeyRoyt — CHANGES_REQUESTED** [review]
Please only run `npm run test:update`, push the updated snapshots and that's it

**Review by SergeyRoyt — APPROVED** [review]
Thanks a lot!
